# Generated by Django 3.2.16 on 2022-10-10 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_post_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='camera',
        ),
        migrations.AddField(
            model_name='post',
            name='camera_filter',
            field=models.CharField(choices=[('compact camera', 'compact camera'), ('dslr camera', 'dslr camera'), ('mirrorless Camera', 'mirrorless camera'), ('action adventure camera', 'action adventure camera'), ('360 camera', '360 camera'), ('medium format camera', 'medium format camera'), ('traditional film camera', 'traditional film camera')], default='normal', max_length=23),
        ),
    ]
