# Generated by Django 3.2.16 on 2022-10-10 11:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='modified_on',
            new_name='updated_at',
        ),
    ]
